version: '3.8'

services:
  nextjs:
    container_name: nextjs_app
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["sh", "-c", "npm install --frozen-lockfile && npm run build && npm run start"]
